######################################################################
# Automatically generated by qmake (1.07a) Wed Jan 13 11:33:06 2010
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

TSM_CLIENT_MODULES += test.tsm

TSM_OUTPUT_DIR = .tsm

CONFIG += tsm

# Input
SOURCES += test.cpp

